#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : CGNS
Version  : 4.4.0
Release  : 11
URL      : https://github.com/CGNS/CGNS/archive/v4.4.0/CGNS-4.4.0.tar.gz
Source0  : https://github.com/CGNS/CGNS/archive/v4.4.0/CGNS-4.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Zlib zlib-acknowledgement
Requires: CGNS-bin = %{version}-%{release}
Requires: CGNS-lib = %{version}-%{release}
Requires: CGNS-license = %{version}-%{release}
Requires: CGNS-openmpi = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glu-dev
BuildRequires : hdf5-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libXmu-dev
BuildRequires : modules
BuildRequires : openmpi-dev
BuildRequires : openssh
BuildRequires : tk-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The CFD General Notation System (CGNS) provides a standard for recording
and recovering computer data associated with the numerical solution of fluid
dynamics equations.

%package bin
Summary: bin components for the CGNS package.
Group: Binaries
Requires: CGNS-license = %{version}-%{release}

%description bin
bin components for the CGNS package.


%package dev
Summary: dev components for the CGNS package.
Group: Development
Requires: CGNS-lib = %{version}-%{release}
Requires: CGNS-bin = %{version}-%{release}
Requires: CGNS-openmpi = %{version}-%{release}
Provides: CGNS-devel = %{version}-%{release}
Requires: CGNS = %{version}-%{release}

%description dev
dev components for the CGNS package.


%package lib
Summary: lib components for the CGNS package.
Group: Libraries
Requires: CGNS-license = %{version}-%{release}

%description lib
lib components for the CGNS package.


%package license
Summary: license components for the CGNS package.
Group: Default

%description license
license components for the CGNS package.


%package openmpi
Summary: openmpi components for the CGNS package.
Group: Default

%description openmpi
openmpi components for the CGNS package.


%prep
%setup -q -n CGNS-4.4.0
cd %{_builddir}/CGNS-4.4.0

%build
## build_prepend content
export FFLAGS="$FFLAGS -fallow-argument-mismatch"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719516335
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DCMAKE_SKIP_INSTALL_RPATH:BOOL=ON \
-DCGNS_ENABLE_PARALLEL:BOOL=OFF \
-DCGNS_ENABLE_HDF5:BOOL=ON \
-DHDF5_NEED_MPI:BOOL=OFF \
-DCGNS_BUILD_CGNSTOOLS:BOOL=OFF \
-DCGNS_BUILD_TESTING:BOOL=ON \
-DCGNS_ENABLE_64BIT:BOOL=ON \
-DCGNS_ENABLE_FORTRAN:BOOL=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
mkdir -p clr-build-openmpi
pushd clr-build-openmpi
. /usr/share/defaults/etc/profile.d/modules.sh
module load openmpi
## build_prepend content
export FFLAGS="$FFLAGS -fallow-argument-mismatch"
## build_prepend end
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=$MPI_ROOT -DCMAKE_INSTALL_SBINDIR=$MPI_BIN \
-DCMAKE_INSTALL_LIBDIR=$MPI_LIB -DCMAKE_INSTALL_INCLUDEDIR=$MPI_INCLUDE -DLIB_INSTALL_DIR=$MPI_LIB \
-DBUILD_SHARED_LIBS:BOOL=ON -DLIB_SUFFIX=64 \
-DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
 .. -DCMAKE_SKIP_INSTALL_RPATH:BOOL=ON \
-DCGNS_ENABLE_HDF5:BOOL=ON \
-DCGNS_ENABLE_PARALLEL:BOOL=ON \
-DHDF5_NEED_MPI:BOOL=ON \
-DCGNS_BUILD_CGNSTOOLS:BOOL=OFF \
-DCGNS_BUILD_TESTING:BOOL=ON \
-DCGNS_ENABLE_64BIT:BOOL=ON \
-DCGNS_ENABLE_FORTRAN:BOOL=ON
make  %{?_smp_mflags}
module unload openmpi
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../clr-build-openmpi;
module load openmpi
export OMPI_MCA_rmaps_base_oversubscribe=1
make test
module unload openmpi

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719516335
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/CGNS
cp %{_builddir}/CGNS-%{version}/license.txt %{buildroot}/usr/share/package-licenses/CGNS/f780297d8a4c3457ad613e1170894b5de854b4d3 || :
cp %{_builddir}/CGNS-%{version}/src/LICENSE %{buildroot}/usr/share/package-licenses/CGNS/f780297d8a4c3457ad613e1170894b5de854b4d3 || :
cp %{_builddir}/CGNS-%{version}/src/cgnstools/LICENSE %{buildroot}/usr/share/package-licenses/CGNS/a429c0e28adfbea645b03002dacff5f40d46da4c || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-openmpi
module load openmpi
%make_install_openmpi
module unload openmpi
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64
mv %{buildroot}/usr/lib/* %{buildroot}/usr/lib64
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/adf2hdf
/usr/bin/cgnscheck
/usr/bin/cgnscompress
/usr/bin/cgnsconvert
/usr/bin/cgnsdiff
/usr/bin/cgnslist
/usr/bin/cgnsnames
/usr/bin/cgnsupdate
/usr/bin/hdf2adf

%files dev
%defattr(-,root,root,-)
/usr/include/cgns.mod
/usr/include/cgnsBuild.defs
/usr/include/cgns_io.h
/usr/include/cgnsconfig.h
/usr/include/cgnslib.h
/usr/include/cgnstypes.h
/usr/include/cgnstypes_f.h
/usr/include/cgnstypes_f03.h
/usr/include/cgnswin_f.h
/usr/lib64/cmake/cgns/cgns-targets-relwithdebinfo.cmake
/usr/lib64/cmake/cgns/cgns-targets.cmake
/usr/lib64/libcgns.so
/usr/lib64/openmpi/include/cgns.mod
/usr/lib64/openmpi/include/cgnsBuild.defs
/usr/lib64/openmpi/include/cgns_io.h
/usr/lib64/openmpi/include/cgnsconfig.h
/usr/lib64/openmpi/include/cgnslib.h
/usr/lib64/openmpi/include/cgnstypes.h
/usr/lib64/openmpi/include/cgnstypes_f.h
/usr/lib64/openmpi/include/cgnstypes_f03.h
/usr/lib64/openmpi/include/cgnswin_f.h
/usr/lib64/openmpi/include/pcgnslib.h
/usr/lib64/openmpi/lib/cmake/cgns/cgns-targets-relwithdebinfo.cmake
/usr/lib64/openmpi/lib/cmake/cgns/cgns-targets.cmake
/usr/lib64/openmpi/lib/libcgns.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcgns.so.4.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/CGNS/a429c0e28adfbea645b03002dacff5f40d46da4c
/usr/share/package-licenses/CGNS/f780297d8a4c3457ad613e1170894b5de854b4d3

%files openmpi
%defattr(-,root,root,-)
/usr/lib64/openmpi/bin/adf2hdf
/usr/lib64/openmpi/bin/cgnscheck
/usr/lib64/openmpi/bin/cgnscompress
/usr/lib64/openmpi/bin/cgnsconvert
/usr/lib64/openmpi/bin/cgnsdiff
/usr/lib64/openmpi/bin/cgnslist
/usr/lib64/openmpi/bin/cgnsnames
/usr/lib64/openmpi/bin/cgnsupdate
/usr/lib64/openmpi/bin/hdf2adf
/usr/lib64/openmpi/lib/libcgns.so.4.4
